import Dashboard from "../../../components/dashboard/dashboard";
import AdminMain from "../../../components/dashboard/admin/main/main";
import Head from "next/head";
import { Fragment } from "react";
const DashboardPage = (props) => {
  return (
    <Fragment>
      <Head>
        <title>لوحة التحكم - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Dashboard>
        <AdminMain />
      </Dashboard>
    </Fragment>
  );
};

export default DashboardPage;
