import Head from "next/head";
import HomePage from "../components/home/HomePage";
import { Fragment } from "react";
import data from "../data/data.json";

export default function Home(props) {
  return (
    <Fragment>
      <Head>
        <title>دار الألعاب - Games Dar</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <HomePage data={data} />
    </Fragment>
  );
}

export async function getStaticProps() {
  if (!data) {
    return {
      redirect: {
        destination: "/no-data",
      },
    };
  }
  return {
    props: {
      data: data,
    },
    revalidate: 10,
  };
}
